language: cpp

compiler:
    - gcc
    - clang

env:
    - LUA=lua5.1

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get -qq update
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    - source .travis/setenv_lua.sh

before_script:
    - export LUA_DIR=$TRAVIS_BUILD_DIR/install/lua
    - cd tests
    - cmake . && make

script:
    - ctest -V
