language: cpp

compiler:
    - gcc

install:
    - curl http://www.lua.org/ftp/lua-5.1.5.tar.gz | tar xz
    - mv lua-5.1.5 lua
    - cd lua
    - make linux
    - make INSTALL_TOP=$TRAVIS_BUILD_DIR/install/lua install
    - cd ..

before_script:
    - export LUA_DIR=$TRAVIS_BUILD_DIR/install/lua
    - cd tests
    - ls $LUA_DIR
    - cmake . && make

script:
    - ctest -V
